"""Single source for the LLM-facing tool catalog and fix taxonomy.

The tool list is rendered from `REGISTRY`, so the prompt the model sees cannot
drift from the tools that actually exist / are validated / are applied. Prompt
*craft* (when to reach for each fix, naming advice) lives in `FIX_TAXONOMY`
here, next to the catalog it annotates.

Consumers: `flowbook/server/fix_suggester.py` (prompt assembly) and the
generated `flowbook/docs/_generated/tool_catalog.md` (kept in sync by a test).
"""

from __future__ import annotations

from typing import List, Optional

from flowbook.tools.registry import REGISTRY, Tool


def _signature(tool: Tool) -> str:
    params = list((tool.parameters.get("properties") or {}).keys())
    return f"{tool.name}({', '.join(params)})"


def render_tool_catalog(tools: Optional[List[Tool]] = None) -> str:
    """Render the registry as a markdown bullet list: ``- `name(args)` — desc``."""
    tools = REGISTRY if tools is None else tools
    return "\n".join(f"- `{_signature(t)}` — {t.description}" for t in tools)


def render_function_schemas(schemas: List[dict]) -> str:
    """Render OpenAI/litellm function-call schemas as a markdown bullet list.

    Used to render an agent's available-tool prose directly from the schemas it
    is actually given, so the prompt can't drift from the tool set (the
    custom-fix agent's inspect/mutate tools live in
    ``fix_tools_readonly``/``fix_tools_mutator``, not the registry).
    """
    lines: List[str] = []
    for schema in schemas:
        fn = schema.get("function") or {}
        params = list(((fn.get("parameters") or {}).get("properties") or {}).keys())
        lines.append(
            f"- `{fn.get('name', '?')}({', '.join(params)})` — "
            f"{fn.get('description', '')}"
        )
    return "\n".join(lines)


# Prompt-craft guidance that annotates the catalog. Concise; the per-tool
# one-liners come from the registry via render_tool_catalog().
FIX_TAXONOMY = """# Choosing a fix

- Reach for `alpha_rename` when a name is reused for different purposes, or a
  sequential transform overwrites a name already read above. Choose a
  *semantically meaningful* new_name (`train_combined`, `lr_model`,
  `df_featured`) — never `df2`, `df_new`, or `model_v2`. The chosen variable
  name must literally appear in the named cell's source.
- Reach for `remove_inplace` for UNRECOVERABLE_MUTATION from pandas
  `inplace=True` calls; for `insert_deepcopy` when an object is mutated in place
  by a method (e.g. `model.fit()`) and the binding must be preserved.
- Reach for `mark_diagnostic` / `move_cell` for pure inspection cells
  (`df.info()`, `df.head()`, plots) that sit above or interleave with a
  mutation; for `merge_cells` when an allocation and its tightly-coupled
  transformation are split and would be clearer as one atomic unit.
- `cell_id`, `after_cell_id`, and members of `cell_ids` must be drawn from the
  cell order you are given."""


def render_tool_catalog_doc() -> str:
    """Full text of the generated docs/_generated/tool_catalog.md file."""
    return (
        "<!-- GENERATED by flowbook.tools.prompt.render_tool_catalog_doc(); "
        "do not edit by hand. Regenerate when REGISTRY changes. -->\n"
        "# FlowBook tool catalog\n\n"
        "The reproducibility tools every LLM surface (MCP, NBI, in-product "
        "fix-it) shares, defined once in `flowbook/tools/registry.py`.\n\n"
        f"{render_tool_catalog()}\n"
    )
