"""CLI tool to display errors from a comparison JSON file.

Given a comparison JSON file (generated by compare-baseline), this tool displays
detailed information about each reproducibility error, including:
- Error type and affected variables
- Causer cell (if any)
- Full source code of the cell where the error occurred

Usage:
    python -m flowbook.cli.show_errors comparison.json
    python -m flowbook.cli.show_errors comparison.json --notebook path/to/notebook.ipynb
    python -m flowbook.cli.show_errors comparison.json --notebook-dir /local/path/to/notebooks
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


def load_json(path: str) -> Dict[str, Any]:
    """Load a JSON file."""
    with open(path, "r") as f:
        return json.load(f)


def load_notebook(path: str) -> Dict[str, Any]:
    """Load a notebook file."""
    with open(path, "r") as f:
        return json.load(f)


def resolve_notebook_path(json_path: str, notebook_dir: str) -> Optional[str]:
    """Resolve notebook path by finding matching suffix under notebook_dir.

    Given a JSON path like '/shared/remote/KaggleBenchmarks/s5e1/notebook.ipynb'
    and notebook_dir '/Users/local/KaggleBenchmarks', this finds the notebook
    by progressively trying path suffixes:
        1. /Users/local/KaggleBenchmarks/s5e1/notebook.ipynb
        2. /Users/local/KaggleBenchmarks/notebook.ipynb

    Args:
        json_path: The notebook path from the JSON metadata
        notebook_dir: Local directory that should contain the notebook

    Returns:
        Resolved local path if found, None otherwise
    """
    json_p = Path(json_path)
    dir_p = Path(notebook_dir)

    # Get all path components after root
    parts = json_p.parts
    if not parts:
        return None

    # Try progressively shorter suffixes
    # Start with just the filename, then add parent directories
    for i in range(len(parts) - 1, 0, -1):
        suffix = Path(*parts[i:])
        candidate = dir_p / suffix
        if candidate.exists():
            return str(candidate)

    return None


def get_cell_source(notebook: Dict[str, Any], cell_id: str) -> Optional[str]:
    """Get the source code for a cell by ID."""
    for cell in notebook.get("cells", []):
        metadata = cell.get("metadata", {})
        # Cell ID can be in metadata.id or metadata.cell_id
        cid = metadata.get("id") or metadata.get("cell_id")
        if cid == cell_id:
            source = cell.get("source", "")
            if isinstance(source, list):
                return "".join(source)
            return source
    return None


def get_cell_by_index(notebook: Dict[str, Any], index: int) -> Optional[Dict[str, Any]]:
    """Get a cell by its code cell index (markdown cells don't count)."""
    code_cells = [c for c in notebook.get("cells", []) if c.get("cell_type") == "code"]
    if 0 <= index < len(code_cells):
        return code_cells[index]
    return None


def format_error(error: Dict[str, Any]) -> str:
    """Format a single error for display."""
    error_type = error.get("error_type", "unknown")
    locations = error.get("locations", [])
    causer_cell = error.get("causer_cell")
    accepted = error.get("accepted", False)

    parts = [f"  Type: {error_type}"]
    if locations:
        parts.append(f"  Variables: {', '.join(locations)}")
    if causer_cell:
        parts.append(f"  Causer Cell: {causer_cell}")
    parts.append(f"  Accepted: {accepted}")

    return "\n".join(parts)


def format_cell_source(source: str, max_lines: Optional[int] = None) -> str:
    """Format cell source code with line numbers.

    Args:
        source: The source code string
        max_lines: Maximum lines to show (None = no limit)
    """
    lines = source.split("\n")
    total_lines = len(lines)
    truncated = max_lines is not None and total_lines > max_lines

    if truncated:
        lines = lines[:max_lines]

    formatted = []
    for i, line in enumerate(lines, 1):
        formatted.append(f"  {i:3d} | {line}")

    if truncated:
        formatted.append(f"  ... ({total_lines - max_lines} more lines)")

    return "\n".join(formatted)


def build_cell_id_to_index(comparison: Dict[str, Any]) -> Dict[str, int]:
    """Build a mapping from cell_id to cell_index from comparison data."""
    mapping = {}
    kernels = comparison.get("kernels", {})
    flowbook = kernels.get("flowbook", {})
    timing = flowbook.get("timing", {})
    cells = timing.get("cells", [])

    for cell in cells:
        cell_id = cell.get("cell_id")
        cell_index = cell.get("cell_index")
        if cell_id is not None and cell_index is not None:
            mapping[cell_id] = cell_index

    return mapping


def extract_errors(comparison: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Extract all cells with errors from comparison data."""
    errors = []

    # Get flowbook timing cells
    kernels = comparison.get("kernels", {})
    flowbook = kernels.get("flowbook", {})
    timing = flowbook.get("timing", {})
    cells = timing.get("cells", [])

    for cell in cells:
        status = cell.get("status", "ok")
        if status in ("violation", "error"):
            checking_result = cell.get("checking_result", {})
            cell_errors = checking_result.get("errors", [])

            if cell_errors:
                errors.append({
                    "cell_id": cell.get("cell_id"),
                    "cell_index": cell.get("cell_index"),
                    "status": status,
                    "error_summary": cell.get("error"),
                    "errors": cell_errors,
                    "reasons": checking_result.get("reasons", []),
                })

    return errors


def get_cell_source_by_id_or_index(
    notebook: Dict[str, Any],
    cell_id: str,
    cell_id_to_index: Dict[str, int],
) -> Optional[str]:
    """Get cell source by ID, falling back to index lookup."""
    # Try by ID first
    source = get_cell_source(notebook, cell_id)
    if source:
        return source

    # Fall back to index lookup using the mapping
    cell_index = cell_id_to_index.get(cell_id)
    if cell_index is not None:
        cell = get_cell_by_index(notebook, cell_index)
        if cell:
            src = cell.get("source", "")
            if isinstance(src, list):
                src = "".join(src)
            return src

    return None


def display_errors(
    comparison: Dict[str, Any],
    notebook: Optional[Dict[str, Any]],
    show_source: bool = True,
    max_lines: Optional[int] = None,
) -> int:
    """Display all errors from comparison data.

    Returns:
        Number of errors found
    """
    errors = extract_errors(comparison)
    cell_id_to_index = build_cell_id_to_index(comparison)

    if not errors:
        print("No errors found in comparison data.")
        return 0

    print(f"\n{'=' * 70}")
    print(f"REPRODUCIBILITY ERRORS ({len(errors)} cells with errors)")
    print(f"{'=' * 70}\n")

    for i, error_info in enumerate(errors, 1):
        cell_id = error_info["cell_id"]
        cell_index = error_info["cell_index"]
        status = error_info["status"]
        error_summary = error_info.get("error_summary", "")

        print(f"[{i}] Cell {cell_id} (index {cell_index}) - {status.upper()}")
        print(f"    Summary: {error_summary}")
        print()

        # Display each error
        for j, error in enumerate(error_info["errors"], 1):
            print(f"  Error {j}:")
            print(format_error(error))
            print()

        # Display reasons (staleness info)
        reasons = error_info.get("reasons", [])
        if reasons:
            print("  Reasons:")
            for reason in reasons:
                reason_type = reason.get("type", "unknown")
                if reason_type == "skipped_upstream":
                    loc = reason.get("loc", "?")
                    expected = reason.get("expected_cell_id", "?")
                    print(f"    - {reason_type}: {loc} (expected from {expected})")
                else:
                    print(f"    - {reason_type}")
            print()

        # Display cell source
        if show_source and notebook:
            # Collect all cells to display: (index, cell_id, role, source)
            cells_to_show = []

            # Add causer cells
            causer_ids = set()
            for error in error_info["errors"]:
                causer = error.get("causer_cell")
                if causer and causer != cell_id:
                    causer_ids.add(causer)

            for causer_id in causer_ids:
                causer_index = cell_id_to_index.get(causer_id, -1)
                causer_source = get_cell_source_by_id_or_index(notebook, causer_id, cell_id_to_index)
                cells_to_show.append((causer_index, causer_id, "Causer", causer_source))

            # Add the error cell
            source = get_cell_source_by_id_or_index(notebook, cell_id, cell_id_to_index)
            cells_to_show.append((cell_index, cell_id, "Error", source))

            # Sort by index (notebook order)
            cells_to_show.sort(key=lambda x: x[0] if x[0] >= 0 else float('inf'))

            # Display in order
            for idx, cid, role, src in cells_to_show:
                idx_str = str(idx) if idx >= 0 else "?"
                if src:
                    print(f"  {role} (cell {cid}, index {idx_str}):")
                    print(format_cell_source(src, max_lines))
                else:
                    print(f"  {role} (cell {cid}): (not found in notebook)")
                print()

        print("-" * 70)
        print()

    return len(errors)


def main():
    parser = argparse.ArgumentParser(
        description="Display errors from FlowBook comparison JSON file(s)."
    )
    parser.add_argument(
        "comparison_files",
        nargs="+",
        help="Path(s) to comparison JSON file(s)",
    )
    parser.add_argument(
        "--notebook",
        "-n",
        help="Path to the notebook file (overrides path in JSON metadata)",
    )
    parser.add_argument(
        "--notebook-dir",
        "-d",
        help="Parent directory containing the notebook; tool will search for matching path suffix",
    )
    parser.add_argument(
        "--no-source",
        action="store_true",
        help="Don't display cell source code",
    )
    parser.add_argument(
        "--max-lines",
        type=int,
        default=None,
        help="Maximum lines of source to display per cell (default: unlimited)",
    )

    args = parser.parse_args()

    total_files = len(args.comparison_files)
    total_errors = 0
    files_with_errors = 0

    for file_idx, comparison_file in enumerate(args.comparison_files, 1):
        # File separator
        if total_files > 1:
            print("\n" + "=" * 78)
            print(f"  FILE {file_idx}/{total_files}: {Path(comparison_file).name}")
            print("=" * 78)

        # Load comparison file
        try:
            comparison = load_json(comparison_file)
        except FileNotFoundError:
            print(f"Error: Comparison file not found: {comparison_file}", file=sys.stderr)
            continue
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON in comparison file: {e}", file=sys.stderr)
            continue

        # Get notebook path from JSON metadata
        metadata = comparison.get("metadata", {})
        json_notebook_path = metadata.get("notebook_path", "")

        # Determine actual notebook path to use
        notebook_path = args.notebook
        if not notebook_path and args.notebook_dir:
            # Try to resolve using notebook_dir
            if json_notebook_path:
                resolved = resolve_notebook_path(json_notebook_path, args.notebook_dir)
                if resolved:
                    notebook_path = resolved
                else:
                    print(f"Warning: Could not find notebook under {args.notebook_dir}", file=sys.stderr)
                    print(f"  JSON path: {json_notebook_path}", file=sys.stderr)
            else:
                print("Warning: No notebook_path in JSON metadata to resolve", file=sys.stderr)

        if not notebook_path:
            notebook_path = json_notebook_path

        if not notebook_path and not args.no_source:
            print("Error: No notebook path found. Provide --notebook, --notebook-dir, or use --no-source.", file=sys.stderr)
            continue

        # Load notebook (optional if --no-source)
        notebook = None
        if not args.no_source:
            try:
                notebook = load_notebook(notebook_path)
            except FileNotFoundError:
                print(f"Warning: Notebook not found: {notebook_path}", file=sys.stderr)
                print("Tip: Use --notebook to specify the correct path, or --no-source to skip source display.", file=sys.stderr)
                print()
            except json.JSONDecodeError as e:
                print(f"Error: Invalid JSON in notebook: {e}", file=sys.stderr)
                continue

        # Display header
        if total_files == 1:
            print(f"\nComparison: {comparison_file}")
        print(f"Notebook:   {Path(notebook_path).name if notebook_path else '(not specified)'}")

        # Display errors
        error_count = display_errors(
            comparison,
            notebook,
            show_source=not args.no_source,
            max_lines=args.max_lines,
        )

        if error_count > 0:
            total_errors += error_count
            files_with_errors += 1
            print(f"\nSubtotal: {error_count} cells with errors in this file")

    # Summary for multiple files
    if total_files > 1:
        print("\n" + "=" * 78)
        print(f"  SUMMARY: {total_errors} errors in {files_with_errors}/{total_files} files")
        print("=" * 78)

    return 0


if __name__ == "__main__":
    sys.exit(main())
