#!/usr/bin/env python3
"""
Parse FlowBook reproducibility error reports and extract structured data.

This script parses error report files generated by FlowBook's comparison tool
and extracts structured information about each notebook's reproducibility errors.

Usage:
    python parse_repro_errors.py ERROR_REPORT_FILE [NOTEBOOKS_DIR]

Example:
    python parse_repro_errors.py errors.txt ../KaggleBenchmarks
"""

import argparse
import json
import re
import sys
from pathlib import Path


def find_notebook_path(notebook_name: str, notebooks_dir: Path) -> str | None:
    """Find the actual path to a notebook given its name.

    Args:
        notebook_name: Name of the notebook file (e.g., "my-notebook.ipynb")
        notebooks_dir: Root directory to search for notebooks

    Returns:
        Full path to the notebook, or None if not found
    """
    pattern = f"**/{notebook_name}"
    matches = list(notebooks_dir.glob(pattern))
    # Filter out .original.ipynb, checkpoints, virtual_documents
    matches = [m for m in matches
               if ".original." not in str(m)
               and "checkpoint" not in str(m)
               and "virtual_documents" not in str(m)]
    if matches:
        return str(matches[0])
    return None


def get_line_ranges(content: str) -> dict[str, tuple[int, int]]:
    """Get line number ranges for each notebook section in the report.

    Args:
        content: Full content of the error report file

    Returns:
        Dict mapping notebook names to (start_line, end_line) tuples
    """
    lines = content.split('\n')
    file_pattern = r'^\s+FILE \d+/\d+: (.+?)_comparison\.json$'

    ranges = {}
    current_notebook = None
    current_start = None

    for i, line in enumerate(lines, 1):
        match = re.match(file_pattern, line)
        if match:
            if current_notebook:
                ranges[current_notebook] = (current_start, i - 1)
            current_notebook = match.group(1)
            current_start = i

    if current_notebook:
        ranges[current_notebook] = (current_start, len(lines))

    return ranges


def parse_errors_file(filepath: str | Path, notebooks_dir: str | Path | None = None) -> dict:
    """Parse an error report file and return structured data about each notebook's errors.

    Args:
        filepath: Path to the error report file
        notebooks_dir: Optional directory to search for notebook files

    Returns:
        Dict mapping notebook names to their error information:
        {
            "notebook.ipynb": {
                "json_name": "notebook",
                "notebook_path": "/full/path/to/notebook.ipynb",
                "error_count": 3,
                "line_range": (10, 150),
                "errors": [
                    {
                        "error_num": 1,
                        "cell_id": "abcd",
                        "cell_index": 5,  # CODE cell index (excludes markdown)
                        "summary": "...",
                        "block": "..."  # Full error block text
                    },
                    ...
                ]
            },
            ...
        }
    """
    filepath = Path(filepath)
    if notebooks_dir:
        notebooks_dir = Path(notebooks_dir)

    with open(filepath, 'r') as f:
        content = f.read()

    # Get line ranges for each file section
    line_ranges = get_line_ranges(content)

    # Split by FILE headers
    file_pattern = r'={70,}\n\s+FILE \d+/\d+: (.+?)_comparison\.json\n={70,}\nNotebook:\s+(.+?\.ipynb)'

    notebooks = {}
    file_matches = list(re.finditer(file_pattern, content))

    for i, match in enumerate(file_matches):
        json_name = match.group(1)
        notebook_name = match.group(2)

        # Get section content (from this match to next match or end)
        start = match.end()
        end = file_matches[i+1].start() if i+1 < len(file_matches) else len(content)
        section = content[start:end]

        # Find notebook path if notebooks_dir provided
        notebook_path = None
        if notebooks_dir:
            notebook_path = find_notebook_path(notebook_name, notebooks_dir)

        # Parse errors in this section
        error_pattern = r'\[(\d+)\] Cell (\w+) \(index (\d+)\) - VIOLATION\n\s+Summary: (.+?)(?=\n\n)'
        errors = []

        for error_match in re.finditer(error_pattern, section, re.DOTALL):
            error_num = int(error_match.group(1))
            cell_id = error_match.group(2)
            cell_index = int(error_match.group(3))
            summary = error_match.group(4).strip()

            # Extract the full error block for context
            block_start = error_match.start()
            # Find next error or end of section
            next_error = re.search(r'\n-{70}', section[block_start:])
            block_end = block_start + next_error.end() if next_error else len(section)
            error_block = section[block_start:block_end]

            errors.append({
                'error_num': error_num,
                'cell_id': cell_id,
                'cell_index': cell_index,
                'summary': summary,
                'block': error_block
            })

        notebooks[notebook_name] = {
            'json_name': json_name,
            'notebook_path': notebook_path,
            'error_count': len(errors),
            'line_range': line_ranges.get(json_name),
            'errors': errors
        }

    return notebooks


def print_summary(data: dict) -> None:
    """Print a human-readable summary of the parsed errors."""
    total_errors = sum(info['error_count'] for info in data.values())
    notebooks_with_errors = sum(1 for info in data.values() if info['error_count'] > 0)

    print(f"Total: {total_errors} errors across {notebooks_with_errors} notebooks")
    print(f"({len(data)} notebooks analyzed, {len(data) - notebooks_with_errors} clean)\n")

    for nb, info in data.items():
        if info['error_count'] > 0:
            path_info = f", path={info['notebook_path']}" if info['notebook_path'] else ""
            line_info = f", lines {info['line_range'][0]}-{info['line_range'][1]}" if info['line_range'] else ""
            print(f"{nb}: {info['error_count']} errors{path_info}{line_info}")
            for e in info['errors']:
                print(f"  [{e['error_num']}] Cell {e['cell_id']} (code index {e['cell_index']})")


def main():
    parser = argparse.ArgumentParser(
        description='Parse FlowBook reproducibility error reports',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('error_file', help='Path to the error report file')
    parser.add_argument('notebooks_dir', nargs='?', help='Directory containing notebooks')
    parser.add_argument('--json', action='store_true', help='Output as JSON')

    args = parser.parse_args()

    data = parse_errors_file(args.error_file, args.notebooks_dir)

    if args.json:
        # Remove 'block' from errors for cleaner JSON output
        clean_data = {}
        for nb, info in data.items():
            clean_info = {**info}
            clean_info['errors'] = [
                {k: v for k, v in e.items() if k != 'block'}
                for e in info['errors']
            ]
            clean_data[nb] = clean_info
        print(json.dumps(clean_data, indent=2))
    else:
        print_summary(data)


if __name__ == '__main__':
    main()
